sig:
  algo: "sac"
  reward: "xy_diff"
  penalty: "z_lim-collision_penalty-boundary_penalty"
  obs: "kin_obst_bait_compressed_sensor_obs"
  act: "vel"
  others: ""
nn:
  netArch: [512, 384]
  activationFn: "relu"
obst:
  visionAngle: 120
  nSegments: 120
  compressionParam: 12
aviary:
  nEpisodes: 750
  simFreq: 240
  avEpisodeSteps: 3600
  collisionDistance: 0.12
  isStrictBoundary: True
  isStrictDeath: False
  baitResetFreq: 5
  evalFreq: 5000