sig:
  algo: "sac"
  reward: "rew_relaxed"
  penalty: "severe_death"
  obs: "kin_obs"
  act: "vel"
  others: "shinobi-hello_world"
nn:
  netArch: [400, 300]
  activationFn: "relu"
obst:
  visionAngle: 120
  nSegments: 121
aviary:
  nEpisodes: 5000
  avEpisodeSteps: 250
  isStrictDeath: True
  baitResetFreq: 10
  evalFreq: 2000